### PR TITLE
Fixed enum34 conditional requirement to support poetry installs

### PR DESCRIPTION
**Pull request by timharris777**
This change moves the conditional requirement of enum34 into the requirements file with appropriate python version condition.

This update is necessary because `poetry add log_symbols` does not support the way that enum34 i currently being conditionally installed.

I have tested the code to make sure it conditionally install or does not install correctly.

Let me know if you have any questions. 

Thanks!

### CODE REVIEW

**Comment by timharris777** [comment]
@manrajgrover , let me know if you have any questions. Thanks!

**Comment by manrajgrover** [comment]
Hi @timharris777,

Thanks for making this change. :100: Kindly fix the build process for AppVeyor before I merge this.

**Comment by timharris777** [comment]
@manrajgrover , I was able to get appveyor builds to finish successfully only by commenting out the python3.4 section in the appveyor.yaml file. I troubleshot for a while and all the build failures seemed to be due to an issue with the 3.4 environment on windows not being set up correctly. All of my local builds on 3.4 worked just fine. I commented it out and sure enough all other builds succeeded. Not sure how you want to proceed.

**Comment by timharris777** [comment]
@manrajgrover , any updates?

**Comment by timharris777** [comment]
@manrajgrover , can you accept my pull request?

**Comment by manrajgrover** [comment]
Hi @timharris777,

Apologies for the delay. I'll have a look at this sometime today. But I'm not happy with removing Appveyor 3.4 just because installation is failing on it.

**Review by manrajgrover — APPROVED** [review]
LGTM! Merging! :100:

**Pull request merged**
